kind: Secret
apiVersion: v1
metadata:
  name: pgbouncer-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
type: Opaque
data:
  userlist.txt: {{ include "pgbouncer.userlist.txt" . | b64enc }}
